[package]
name = "immich-rs-cli"
description = "Command-line interface for immich-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ctrlc.workspace = true
immich-rs-application = { path = "../immich-application", version = "=0.1.0-rc.1" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
immich-rs-core = { path = "../immich-core", version = "=0.1.0-rc.1" }
immich-rs-sources = { path = "../immich-sources", version = "=0.1.0-rc.1" }
serde_json.workspace = true

[[bin]]
name = "immich-rs"
path = "src/main.rs"

[lints]
workspace = true
